riscv/riscv-binutils-gdb

gdb/config/riscv/linux.mh
gdb/configure.host
gdb/riscv-linux-tdep.c
gdb/riscv-tdep.c
gdb/riscv-tdep.h

It looks like the merge of the native GDB patches didn't go correctly and ended up producing something that doesn't even build.  This PR submits some patches that make the RISC-V native GDB port build.  I haven't tested anything (and the last patch is a mess), but I thought I'd get this out there just in case anyone was working on it because I might not have time to finish this for a bit.
At least it can't be worse than code that doesn't build... :)

Make GDB compile in native mode

---

sim/riscv/sim-main.c
sim/riscv/sim-main.h

There were references to several registers in sim-main.c that don't
exist in riscv-opc.h.
A print macro was used that wasn't defined anywhere.
tconfig.h wasn't included, which resulted in some MACH_ macros not being
defined.
I have no idea how this ever built for somebody.

Fix gdb build.

---

gdb/riscv-tdep.c

That's a MIPS thing.
This fixes gdb debugging 32-bit code where bit 31 of the address is set.

32-bit addresses should not be sign-extended.

---

gdb/riscv-tdep.c
gdb/riscv-tdep.h

Users can use this register to inspect and change the privilege level of
the core. It doesn't make any assumptions about the actual underlying
debug mechanism (as opposed to having the user change DCSR directly,
which may not exist in all debug implementations).

Add support for virtual priv register.

---

sim/riscv/sim-main.c

- According spec result is -2^31 is only when divisor is -1 AND dividend
is -2^31 for divw.
- According spec result is 0 is only when divisor is -1 AND dividend
is -2^31 for remw.

Fix wrong behavior for divw and remw

---

sim/riscv/sim-main.c

In my environment CLOCK_BOOTTIME is missing. For this case I suggest to revert to CLOCK_MONOTONIC. 
A little poking on this topic revealed that this could be a reason for platform incompatibility. According to different forums OSX doesn't have clock_gettime (I don't use OSX so couldn't confirm), other OSes would have different enums for clock IDs. My CentOS is happy with CLOCK_MONOTONIC but perhaps worth a more robust solution, especially if someone can try on other OSes. Until then would be good to have this hack in since riscv-tools build fails without it.

fixing compilation error with older linux env

---

sim/riscv/sim-main.c

- it's may generate wrong result with -O2 -fno-wrapv,
but generate right result with -O2 -fwrapv when input
1 and -9223372036854775808(0x8000000000000000).

Don't implment mulhu with __int128

---

bfd/elfnn-riscv.c
ld/emulparams/elf32lriscv-defs.sh

"_gp" could conflict with ABI-complient code.  While it's probably OK
because MIPS uses this name, we figured it'd be good to clean this up
before a release with RISC-V in it.
ld/ChangeLog:
2017-02-08  Palmer Dabbelt  <palmer@dabbelt.com>
* emulparams/elf32lriscv-defs.sh (SDATA_START_SYMBOLS): Change
_gp to __global_pointer$.
bfd/ChangeLog:
2017-02-08  Palmer Dabbelt  <palmer@dabbelt.com>
* elfnn-riscv.c (riscv_global_pointer_value): Change _gp to
__global_pointer$.

Don't use "_gp" on RISC-V, use "_global_pointer$" instead

---

gdb/riscv-tdep.c
gdb/riscv-tdep.h

This allows people to force the gdb to use or not use compressed
breakpoints, in case misa isn't accessible to determine this
automatically. Specifically, there's a user whose core does not support
compressed instructions but misa is not where gdb expects it to be
because it was moved in the 1.9.1 privileged spec.

Compressed breakpoint option

---

opcodes/riscv-opc.c

e.g.
1:  auipc ra, %pcrel_hi(symbol)
jalr  ra, %pcrel_lo(1b)(ra)
The use of ra instead of t1 for address construction provides an opportunity for a microarchitecture to elide the write of the destination address, and instead read the target address as an immediate spread across the fused auipc+jalr pair. The link register ra in the jalr overwrites the target address temporary.
I've compiled the toolchain, built linux-kernel and boot tested it. Here is a snippet of objdump output after the change:
```
ffffffff80000134:	001b4097          	auipc	ra,0x1b4
ffffffff80000138:	6f6080e7          	jalr	1782(ra) # ffffffff801b482a <strcmp>
```

Change CALL macro to use ra as the temporary address register

---

bfd/elfnn-riscv.c
bfd/elfxx-riscv.c
bfd/elfxx-riscv.h
gas/config/tc-riscv.c
ld/emultempl/riscvelf.em

In the medany code model the compiler generates PCREL_HI20+PCREL_LO12
relocation pairs against local symbols because HI20+LO12 relocations
can't reach high addresses.  We relax HI20+LO12 pairs to GPREL
relocations when possible, which is an important optimization for
Dhrystone.  Without this commit we are unable to relax
PCREL_HI20+PCREL_LO12 pairs to GPREL when possible, causing a XX%
permormance hit on Dhrystone on Rocket.
Note that we'll now relax
la gp, __global_pointer$
to
mv gp, gp
which probably isn't what you want in your entry code.  Users who want
gp-relative symbols to continue to resolve should add ".option norelax"
accordingly.  Due to this, the assembler now pairs PCREL relocations
with RELAX relocations when they're expected to be relaxed.

RISC-V: Relax RISCV_PCREL_* to RISCV_GPREL_*

---

gas/config/tc-riscv.c

2017-07-25  Andrew Waterman  <andrew@sifive.com>
* config/tc-riscv.c (riscv_set_arch): Obviate use-after-free.

Fix use-after free bug

---

gas/config/tc-riscv.c

@kito-cheng on the Binutils mailing list, Klaus Pedersen pointed out that the Q extension not be a special case in ISA-string parsing.  I believe he's correct; this patch simplifies the code and enforces the ISA-string spec (Q must come after D and before C).

Don't treat Q extension as special case

---

opcodes/riscv-opc.c

This fixes "-M noaliases" disassembly for these instructions.
opcodes/ChangeLog
2017-08-01  Palmer Dabbelt  <palmer@dabbelt.com>
* riscv-opc.c (riscv_opcodes): Mark "c.jr", "c.j", "c.mv",
"c.lui" and "c.li" as aliases.

RISC-V: Mark various compressed aliases as aliases

---

gdb/riscv-tdep.c

I assume this is just some old cut-and-paste code. Without this change,
the machine interface reports a large number of unnamed registers at the
end of the real list in response to `data-list-register-names`.

We don't implement any pseudoregisters.

---

gdb/riscv-tdep.c

This should cause the machine interface register list to list the ABI
names, which in turn will cause them to show up that way in Eclipse.
(Eclipse can apparently not give the registers useful names itself.)
This fixes https://github.com/riscv/riscv-openocd/issues/93

Use ABI names for registers.

---

gdb/arch-utils.c
gdb/gdbarch.c
gdb/gdbarch.h
gdb/riscv-tdep.c

The real fix here is to use the gdbarch_ functions instead of the riscv_ ones when displaying registers. Without that, the target description isn't checked which means that (sometimes) you'd get registers showing up that aren't actually on the target.
While discovering that this was the problem, I made some changes on the way that I think are beneficial to keep:
1. Add a few comments to undocumented gdb internal structures.
2. Factor out the register initialization into its own function.

Don't show registers that don't exist

---

gdb/Makefile.in
gdb/configure.nat

This fixes native gdb builds.  Tested with a canadian cross build.  It links with the patch, and fails to link without the patch.  Not execution tested, as I don't have an environment for that.
This fixes issue #96.

Make native gdb builds work.

---

sim/riscv/sim-main.c

Link is a POSIX system call that mingw does not support.  This causes build failures on Windows.  If we need this link support then it has to be done differently.  For now, we can just ifdef it out.

Fix mingw builds on Windows.

---

gas/testsuite/gas/riscv/riscv.exp

Minor problem, some gas testcases are accidentally being run twice due to a merge error.

Fix merge error from FSF, glob means we no longer list all tests.

---

ld/testsuite/lib/ld-lib.exp

This fixes over 150 ld testsuite failures for riscv*-elf targets, by not running shared library tests on the embedded elf target that doesn't support shared libraries.  I pushed a patch upstream, but the code has changed recently upstream, so we need a different patch for our release tree.

RISC-V: Disable shared library tests for embedded elf.

---

gas/config/tc-riscv.c
gdb/riscv-tdep.c

gas/
* config/tc-riscv.c (md_parse_option) <OPTION_MABI>: Add missing else
for ilp32e check.
gdb/
* riscv-tdep.c (riscv_extract_return_value): Use regs->arch ()
instead of get_regcache_arch.
(riscv_store_return_value): Likewise.

RISC-V: Patches to fix build on riscv-next branch.

---

gdb/riscv-tdep.c

Previously `info all-registers` and `info registers all` would terminate
as soon as it got to a register that was not readable. Now the user gets
a message and the register list continues.

Complete full reg list if some aren't readable

---

gdb/riscv-tdep.c

This is a fix for https://github.com/riscv/riscv-openocd/issues/295
The RISC-V debug spec 0.13 recommends that write triggers fire before
the write is committed. If the target follows this behaviour, then
have_nonsteppable_watchpoint needs to be set to 1 so that GDB will step
over the watchpoint before checking if the value has changed.
This patch adds a setshow for have_nonsteppable_watchpoint which defaults
to 1 to match the recommended behaviour. If a target does not follow
this timing, then 'set riscv have_nonsteppable_watchpoint 0' will need
to be issued on the command line.
Note: I will also submit a patch to upstream GDB

RISC-V: enable have_nonsteppable_watchpoint by default

---

gas/config/tc-riscv.c
gas/testsuite/gas/riscv/vector-insns-fail-01.d
gas/testsuite/gas/riscv/vector-insns-fail-02.d
gas/testsuite/gas/riscv/vector-insns-fail-03.d
gas/testsuite/gas/riscv/vector-insns-fail-04.d
gas/testsuite/gas/riscv/vector-insns-fail-05.d
gas/testsuite/gas/riscv/vector-insns-fail-06.d
include/opcode/riscv.h
opcodes/riscv-dis.c
opcodes/riscv-opc.c

I get the request recently that the assembler's constraints checking break hardware exception test cases.  As I know, stop to assemble instructions with constraints is reasonable to me.  But it is hard to check whether the hardware  exceptions work expected for the constraints.  For now, the compromises are use the hard cored instruction (.word or .2byte) and .insn directives to build the test cases.  But I think the current test cases won't built by them and can not check the exception for constraints.
It seems quite easy to resolve the problem by adding a GAS internal option to disable checking the RVV constraints (always call `match_opcde` to check).  But for the normal ISA (scalar), we have much complex parsing method for the constraints (The same opcode name with different operands, …

Add GAS option to disable the instruction constraints checking.

---

gas/config/tc-riscv.c
gas/testsuite/gas/riscv/v-zero-imm.d
gas/testsuite/gas/riscv/v-zero-imm.s
gas/testsuite/gas/riscv/vector-insns.d
opcodes/riscv-opc.c

There are two issues about the vector compare instructions recently,
1. Convert the pseudo vmsltu.vi/vmsgeu.vi to vmsne.vv/vmseq.vv, when imm is zero. 
(https://github.com/riscv/riscv-binutils-gdb/issues/206)
We convert the pseudo instructions
`vmsltu.vi/vmsgeu.vi  vd, vs1, imm`
to
(imm isn't zero) `vmsleu.vi/vmsgtu.vi  vd, vs1, imm - 1`
(imm is zero)    `vmsne.vv/vmseq.vv    vd, vs1, vs1`
2. Change the expansion for vmsge.vx and vmsgeu.vx with the unmasked va.
(https://github.com/riscv/riscv-binutils-gdb/issues/208)
`vmsge[u].vx v4, v8, a1` should be expanded to `vmslt[u].vx  v4,v8,a1` plus `vmnot.m  v4,v4`.

Change the expansions and conversion for pseudo vector compare instructions (integer and scale).

---

gas/testsuite/gas/riscv/vector-insns.d
gas/testsuite/gas/riscv/vector-insns.s
opcodes/riscv-opc.c

Add new vmmv.m, and keep the old vmcpy.m for the compatibility.  But objdump will show the new one.
I'm updating vector vm constraints since the mask rule is changed recently.  I will adding the 0.9 release tag when I finish them.  But this PR needs to be merged first, since newest vtg and spike will be released today.
Thanks
Nelson

Updated vmmv.m from vmcpy.m.

---

include/opcode/riscv.h
opcodes/riscv-dis.c
opcodes/riscv-opc.c

This reverts commit 9d02802920483d07aee78c375f20ec24c2e1f591.
The original report is as follows,
https://sourceware.org/pipermail/binutils/2020-June/111383.html
And I have sent a patch to fix this on upstream,
https://sourceware.org/pipermail/binutils/2020-June/111405.html
Inlcude the bfd.h in the include/opcode/riscv.h may cause gdbserver fail to build.  I just want to use the `bfd_boolean` in the opcodes/riscv-opc.c, but I didn't realize this cause the build failed.  Revert the commit 9d02802920483d07aee78c375f20ec24c2e1f591 should fix the gdbserver build.
As I know we don't support vector in GDB for now, so this should be fine.  But in case we need to merge the rvv implementation into FSF binutils someday and forgot this issue, revert the commit 9d02802920483d07aee78c375f20ec24c2e1f591 …

Revert "Change the return type of `match_func` and `constraints` flag to `bfd_boolean`."

---

gdb/riscv-tdep.c
gdb/riscv-tdep.h

Debugger needs to access vector CSR registers vl and vlenb when debugging vector programs. So, gdb needs to be able to convert DWARF numbers of CSR to internal register numbers.

RISC-V: Convert CSR dwarf numbers to gdb register numbers.

---

bfd/elfnn-riscv.c
bfd/elfxx-riscv.c
gas/config/tc-riscv.c
gas/testsuite/gas/riscv/attribute-15-unratified.d
opcodes/riscv-opc.c

I created an branch based on 2.32 with RVB, and merge most patch into one, but keep the author info, including list Maxim Blinov as co-author.
And based on the branch made few improvements for emitting right version info of B-extensions and parsing sub-extensions.

[RVB] Handle sub-extension and version info for B.

---

gdb/ChangeLog
gdb/acinclude.m4
gdb/configure

Including bfd.h now also requires including string.h.  Fixes riscv-gnu-toolchain #867.

Backport fix from FSF to fix configure problem caused by ctf patches.
